### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/Split#1]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**split**
Разбивает большой текстовый файл на маленькие файлы фиксированного размера. 

file задаёт имя входного файла.
- Флаг -o ofile  задаёт базовое имя выходного файла. Если параметр отсутствует,  базовое имя выходного файла равняется “x”. Если параметр равен “-”, в качестве базового имени выходного файла следует использовать имя входного файла.
- Флаг -d означает, что выходные файлы следует называть “ofile1, ofile2, ofile3, ofile4 …”, где ofile это базовое имя выходного файла. Если же этот параметр не указан, то файлы должны называться “ofileaa, ofileab, ofileac, ofilead … ofileaz ofileba ofilebb …  ”.
- Флаг -l num указывает размер выходных файлов в строчках. По умолчанию выходные файлы имеют размер в 100 строчек.
- Флаг -с num указывает размер выходных файлах в символах.
- Флаг -n num указывает количество выходных файлов. Размер файлов при этом должен считаться автоматически.

Command line: split [-d] [-l num|-c num|-n num] [-o ofile] file

В случае, когда какое-нибудь из имён файлов указано неверно или одновременно указано несколько флагов управления размером, следует выдать ошибку. 

Кроме самой программы, следует написать автоматические тесты к ней.

Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библиотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на втором шаге, даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**UPD** Также необходимо разработать инструкцию и/или скрипты сборки приложения и его запуска из командной строки (для проверки в реальных условиях).

**Comment by JohnKhandygo** [comment]
По поводу проблемы с тестами. Вы как-то подключали junit к предыдущему проекту. Здесь надо точно также сделать. 

Альтернативный вариант --- использовать какую-нибудь систему сборки, которая умеет управлять проктными зависимостями (то есть сторонними библиотеками, которые Вы хотите использовать в своем проекте). Например, можно использовать [maven](http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html). В этом туториале уже пример с подключенным junit, кстати. Только используйте более новую версию. Версии можно смотреть [здесь](https://mvnrepository.com/). Например, все доступные версии библиотеки junit можно посмотреть [здесь](https://mvnrepository.com/artifact/junit/junit). Вверху списка расположены самые свежие версии, при щелчке по конкретной версии загружается страница, в которой можно скопировать описание зависимости и вставить в pom.xml (основной конфигурационный файл maven, который располагается в корне проекта, на том же уровне, что и папка src). Помимо maven существует еще [gradle](https://gradle.org/guides/). Он более гибкий, но (по крайней мере раньше был) более "геморойный". В современной мире все пользуются одной из этих систем сборок. 

Код еще очень сырой, проверять там особо нечего сейчас, потому что не понятно, к чему Вы придете в процессе разработки. Единственное, что я могу сказать прямо сейчас: в методе `parseByLine` Вы читаете файл дважды (первый раз для того, чтобы количество строк посчитать). Это, конечно, неэффективно, так делать нельзя. Для того, чтобы просто считать файл построчно можно (Вам подходит этот вариант, когда не указан флаг `-n`) лучше использовать любой из подходов, описанных [здесь](https://www.programcreek.com/2011/03/java-read-a-file-line-by-line-code-example/). В случае же, когда необходимо определить размер выходных файлов автоматически (флаг `-n`), видимо, придется оперировать байтами. То есть сначала определить размер файла в байтах, а потом уже его читать посимвольно/побайтово.

**Comment by JohnKhandygo** [comment]
Посмотрел текущий вариант. Сделано очень мало. Даже Ваши тесты сейчас практически бесполезны, потому что работают с сильно hardcoded файлами. Из того, что могу сказать: 
- В `countLines` Вы организовали чтение строк "руками", однако `parserByLines` уже используете более правильный способ. 
- В `countChars` Вы считываете весь файл целиком в память программы. Это очень плохо, поскольку, если, например, необходимо обработать файл размером 2GB, то программе понадобится по крайней мере 2GB оперативной памяти "откусить" (может просто упасть с out of memory, если ей выделили меньше памяти, чем необходимо). 
- В `parserByLines` Вы дважды считываете один и тот же файл. Вообще операция чтения с диска (в данном случае файлов) --- весьма дорогостоящая штука в плане времени работы программы. Но даже если закрыть на это глаза, это не дело. Здесь совершенно точно можно обойтись одним считыванием (просто ходить по строкам и, в зависимости от ее номера, писать в тот же файл, либо заводить новый).

**Comment by JohnKhandygo** [comment]
Окей, как насчет остальных методов? И у Вас все еще нет нормальных тестов, поэтому полноценную проверку я начать не могу. Вот результаты беглого осмотра:

- [ ] Парамтры из ввода так не считывают... Ну по крайней мере, не в Вашем случае. Обычно делают [вот так](https://docs.oracle.com/javase/tutorial/essential/environment/cmdLineArgs.html). Такой подход позволяет использовать различные библиотеки для разбора аргументов командной строки автоматическим образом. Насколько я понимаю, про [вот эту](http://args4j.kohsuke.org/sample.html) на лекциях рассказывали, она вполне подходит. Используя стороннюю библиотеку, Вы избавляете себя от необходимости тестировать кусок кода, который занимается разбором аргументов командной строки. 
- [ ] В примере запуска split --- это просто название программы (как у любой другой консольной команды типа ls/dir). То есть не обязательно требовать, чтобы `"split"` являлось первым символом в вводе. 
- [ ] В коде две `main` функции. Какая из них должна использоваться при запуске из консоли? Удалите вторую.
- [ ] В java все, кроме классов и статических полей принято именовать в [lowerCamelCase](http://wiki.c2.com/?LowerCamelCase).
- [ ] Зачем в `Splitter` так много полей, если они не используются?
- [ ] Вместо непонятных char кодов лучше использовать их обычное строковое представление.
- [ ] А зачем Вам вообще метод `Splitter:makeAlph`? Значения типа `char` можно складывать точно так же, как и обычные числа (типа `'a' + 1` --- это следующий за `'a'` в ascii таблице символ).
- [ ] В `Splitter` всюду захардкожены пути к выходным файлам. Из-за этого у меня Ваш код скорее всего вовсе не запустится. 
- [ ] В `Splitter::parseByLines` Вы используете переменную `prefix` для вычисления суффикса файла. Не очень говорящее название получается. "Нумерация" файлов по усолчанию (которая `aa`, `ab` и т.д.) у Вас некорректно реализована.

**Comment by Alexandro9911** [comment]
Что делать с  захардкожеными путями к выходным файлам? что тогда надо писать вместо пути к файлу?

**Comment by JohnKhandygo** [comment]
Если я нахожусь в директории C:\projects\someDir и зпускаю Вашу программу из консоли с параметром `-d -o out`, то все файлы `out1`, `out2`, ..., `outN` должны располагаться в директории
C:\projects\someDir. В Вашем же случае они всегда создаются черт знает где.

**Comment by Alexandro9911** [comment]
Вопрос по заданию, при флаге `-с num`  пробел или перенос на новую строку считать символом?

**Comment by JohnKhandygo** [comment]
Пробел да, перенос нет.

**Comment by Alexandro9911** [comment]
+1 метод + имя задается адекватно. 
Я не понимаю, что надо написать вместо пути на файл, чтобы он и у вас и у меня работал?

**Comment by JohnKhandygo** [comment]
Метод  `parseByLines` реализован более менее. Все остальные методы в `Splitter` реализованы некорректно.

**Comment by Alexandro9911** [comment]
Вроде разобрался с Сmd
сделал метод деления по количеству файлов, и исправил nameCreator

**Comment by JohnKhandygo** [comment]
Задание зачтено на 4.5 балла за мелкие недочеты.
