### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/Split#4]
- [x] Тестовый сценарий `parseByLinesTest` проверяет только то, что алгоритмы при разных опциях именования файлов работают идентично (и то несколько странным образом), однако не проверяют корректность работы самой логики разбиения файлов на части.
- [ ] После выполнения тестов в дереве проекта появляются файлы lines1.txt - lines3.txt и linesaa.txt - linesac.txt. Эти файлы --- побочный продукт работы тестов и, следовательно, не должны присутствовать в самом проекте. Их необходимо либо удалять после выполнения тестовых сценариев (может быть удобно воспользоваться junit4 аннотацией [`After`](http://junit.sourceforge.net/javadoc/org/junit/After.html)), либо использовать механизм [временных файлов](https://garygregory.wordpress.com/2010/01/20/junit-tip-use-rules-to-manage-temporary-files-and-folders/) из junit4. Второй вариант считается более правильным.
- [x] Добавьте тесты на методы `parseByChars` и `parseByNum`.
- [x] Файл fileread, как и все входные файлы для тестов, принято размещать в директории тестовых ресурсов проекта (в соответствии со [стандартной структурой](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) maven проектов).
- [x] IDE некоторые места подсвечивает желтеньким. Обычно это означает, что Вы делаете что-то не так. При наведении курсора на подсвеченное место, выводится warning сообщение, а если поставить курсор на такое место и нажать ctrl + Enter, то во многих случаях idea сама предложит варианты исправления.

**Comment by Alexandro9911** [comment]
сделал структуру тестовых файлов и тест на `parseByNum`  и убрал что подчеркивает желтым

**Comment by Alexandro9911** [comment]
Сделал все кроме удаления пока что

**Comment by JohnKhandygo** [comment]
Норм
