### ISSUE TITLE
Task 3.0

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/Split#5]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Английские шашки**
Реализовать игру Английские шашки для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила [здесь](https://ru.wikipedia.org/wiki/Английские_шашки)

**Comment by Alexandro9911** [comment]
Проект тут : https://github.com/Alexandro9911/EnglishDraughts

**Comment by Alexandro9911** [comment]
Проект тут: https://github.com/Alexandro9911/EnglDraughts
Он пока еще не доделан, но думаю скоро все будет

**Comment by JohnKhandygo** [comment]
Я уже забыл, мы с Вами договаривались на какую-то конкретную оценку? Вам надо хотя бы 3.5 баллов за это задание получить для того, чтобы 4 за курсовой проект вышла.

**Comment by JohnKhandygo** [comment]
В любом случае напишите, когда будет готово к проверке.

**Comment by Alexandro9911** [comment]
Я сегодня тесты доделаю и думаю вся логика будет готова. На 3.5 было б неплохо

**Comment by JohnKhandygo** [comment]
Окей, главное правила все реализуйте.

**Comment by Alexandro9911** [comment]
Вроде оно готово. Извиняюсь что так поздно залил все,  очень долго мучился с одним тестом и потерял на нем время(

**Comment by JohnKhandygo** [comment]
На 3.5 годится. Устраивает?

**Comment by Alexandro9911** [comment]
Да, в сумме ж получается 4?

**Comment by JohnKhandygo** [comment]
Да.

**Comment by Alexandro9911** [comment]
Да, все устраивает)

**Comment by JohnKhandygo** [comment]
Окей, зачтено на 3.5 балла.
